### ISSUE TITLE
enhance BADS robustness against uninformative parameters?

### ISSUE THREAD

**Issue by kupiqu** [lacerbi/bads#10]
As many others, I use BADS to compare between distinct model mechanisms. In the course of this comparison I test adding and removing parameters that control these further mechanisms.

For practical reasons, it would be great if BADS would be robust against "unused" parameters in a model (that are used in related models). By unused I mean those that are disabled internally in the model, so the model behaves exactly the same no matter the value these parameters take.

I tested this in BADS and it is sensitive to "unused" parameters showing worse optimizations compared to models where these unused parameters are manually removed from optimization.

If it was only for practical reasons, I could understand closing this issue because it's of little conceptual benefit (as said, one can manually remove unused parameters from the list of parameters sent to BADS and thing solved).

However, conceptually, shouldn't the optimization algorithm (especially BADS for its philosophy) realize about uninformative parameters, and minimize spending "time" trying to optimize the value in their dimension?

Also, parameter "information" isn't usually binary as in the example above. But perhaps using this binary example above of used vs. unused parameters would help finding a better way by which BADS prioritizes the direction of convergence following the most "useful" parameters.

I think working on this issue would be interesting in terms of research and I wonder if you ever considered enhancing BADS further in this regard.

I didn't test, but this issue may affect VBMC as well.

**Comment by lacerbi** [comment]
Thanks for the comment!

First, for those who are not aware, BADS supports *explicitly* "unused" parameters in that you can manually tell BADS to ignore certain parameters by setting the upper/lower bounds to some fixed value (see [here](https://github.com/lacerbi/bads/wiki#can-i-set-lb--ub-for-some-variable-to-fix-it-to-a-given-value)).

However, here you mean *automated* detection of unused (or less informative) parameters. That's in theory what "automatic relevance determination" (ARD) kernels do in Gaussian process regression; a dimension that has little or no impact on the target function would have a very large length scale (that is, the function would not change much along that dimension).
And that's more or less what BADS will infer and make use of during the optimization (it uses an ARD kernel). So why does performance decrease if you add "non-informative" dimensions?

Consider that:
1) BADS only builds a *local* GP approximation of the target function. Thus, global properties need to be re-learnt locally, and BADS might keep checking that a parameter has still no influence. This might seem an issue, but in fact is a major perk of the algorithm as it can deal successfully with non-stationarity and other common features that easily break a global, stationary GP.
2) There is more going on in BADS than GP regression, so I can see a few parts in which having a non-informative dimension would still negatively affect and slow down the optimization.

In short, I don't find surprising that BADS performs worse in the case in which more (non-informative) dimensions are provided. That's the cost of not giving the algorithm our prior information that those dimensions are actually useless *globally*. The rest you are suggesting already happens; BADS tends to follow the most promising directions (although of course there is space for improvement).

Finally, the issue of "unused" parameters is going to affect VBMC *even more*, in that VBMC infers *posteriors* so there is no space for "non-informative" dimensions (that is, even dimensions in which the likelihood is flat need to have a non-trivial posterior). Indeed, there may be non-informative directions in the likelihood but for a number of technical reasons (involving Bayesian quadrature), for maximal flexibility the GP needs to be placed on the log posterior (and not on the log likelihood).

**Comment by kupiqu** [comment]
Thanks for the explanatory response :)

> First, for those who are not aware, BADS supports explicitly "unused" parameters in that you can manually tell BADS to ignore certain parameters by setting the upper/lower bounds to some fixed value (see here).

Yes, I am using this already, but from a practical point of view it would be great if BADS would account for it "automagically"

> The rest you are suggesting already happens; BADS tends to follow the most promising directions (although of course there is space for improvement).

Yes, sorry, I didn't mean it doesn't. It works great in that regard actually. Rather, I meant whether there could be some improvement when some parameters' information tends to 0. But I understand better now that it's something very tricky to achieve.

I am quite convinced that it doesn't make much sense, but I still wonder if heuristically disregarding exactly no-informative parameters would be an option to consider.

**Comment by lacerbi** [comment]
> Rather, I meant whether there could be some improvement when some parameters' information tends to 0. But I understand better now that it's something very tricky to achieve.

Tricky indeed! Also consider that BADS is order of magnitudes faster than other Bayesian optimization methods (which unfortunately means that there is not much time to do fancy analyses between iterations).

> I am quite convinced that it doesn't make much sense, but I still wonder if heuristically disregarding exactly non-informative parameters would be an option to consider.

It's something worth considering in general. For example, finding a "principal" subspace of active parameters is one of the approaches used to perform Bayesian optimization in high-dimension. So, a smart approach might be a way to increase the dimensionality of the problems BADS can tackle.

On the other hand, the problem is that of course we don't want this feature to cause issues in other circumstances. In many real case scenarios, a parameter might be "unused" in certain regions but become active elsewhere, so it's hardly a on-off inference; and if there is an *exactly* unused parameter, it probably should be information provided by the user. In fact, for the record, requiring users to actively provide information they have about their problem is a positive thing - there is no such thing as a truly *black box* scenario; we often know more about the problem and there is no reason why this information should be withheld from the algorithm.

**Comment by kupiqu** [comment]
Yes, I agree with all what you said
