### ISSUE TITLE
More than 40 dimensions

### ISSUE THREAD

**Issue by obj999** [lacerbi/bads#11]
Hi,

I found this bads really convenient to use. Really thanks for sharing this!

I am trying to use the functions to solve an optimisation problem with an input of more than 40 dimensions (about 100 dimensions in the worst case). When I run the code, I noticed that Matlab is showing the following error:

"I4_SOBOL - Fatal error!
  The spatial dimension DIM_NUM should satisfy:
    1 <= DIM_NUM <= 40"

I noticed that it is because the function 'i4_sobol.m' does not support more than 40 dimensions. I had a quick check online, and there is no updated Matlab function supporting more than 40 dimsension input. I wonder if there is any existing solution to this? 
Thanks in advance!

**Comment by lacerbi** [comment]
Hi obj999 - yes, the Sobol initialization will fail but BADS will then use another initialization instead (a Latin hypercube sampling: https://en.wikipedia.org/wiki/Latin_hypercube_sampling) and keep running, so what's the issue?
I could remove the warning but it is also a good reminder that BADS is unlikely to work well in high dimension (it's not designed for D >> 20).

**Comment by obj999** [comment]
Thanks for your quick reply Lacerbi! 

I have include a plotting function to show a geometric parameter change during the optimisation process, and observed that some dimensions are not changing for a long time with the increasing of number of function evaluation. So I suspected that it might be the problem of the dimension limitation and the bads was not working properly. 

According to your reply, the bads optimisation should still work properly even with the warning message. So I guess that was just my misunderstanding. It is good to know that bads is unlikely to work well in high dimension. Now I guess I should focus on reconstructing the optimisation problem with lower dimensions...

Many thanks!

**Comment by lacerbi** [comment]
Yes, BADS will still work even with the `I4_SOBOL` failure warning message, it will just use another initialization.
The fact that BADS is unlikely to work well in high dimension is unrelated to the initialization. 
As usual, I warmly recommend users to check out the extensive documentation, both on the [main page](https://github.com/lacerbi/bads) and the [FAQ](https://github.com/lacerbi/bads/wiki).
