### ISSUE TITLE
Shadowing "unwrap"

### ISSUE THREAD

**Issue by gkaguirre** [lacerbi/bads#3]
Loving BADS!

I use a matlab package manager (https://github.com/ToolboxHub/ToolboxToolbox) to handle path dependencies. Therefore, I do not make use of the BADS "install" function.

I have found that the BADs directory must be pre-pended to the matlab path to function. This is because BADs has the function "unwrap"  (.../bads/gpml-matlab-v3.6-2015-07-07/util/unwrap.m) which shadows the built-in matlab function of the same name but has different functionality.

While I have been able to finesse the situation in my case, I thought you might want to know about this conflict and consider giving your function a different name to avoid this collision.

Best,

Geoff

**Comment by lacerbi** [comment]
Excellent point, Geoff. This came up with another user as well.
"unwrap" was part of the GPML toolbox (which is included in the BADS release for convenience, and also because now GPML has moved to a new version).
I renamed "unwrap" to "unwrap2vec", which should fix all issues.

Thanks!
Luigi
