### ISSUE TITLE
warn ID for mesh overflow

### ISSUE THREAD

**Issue by gkaguirre** [lacerbi/bads#4]
I would like to be able to selectively silence the warning:

`Warning: The mesh attempted to expand above maximum size too many times. Try widening PLB and PUB.`

to do so, the warning needs to have an associated warning identifier. May I propose that line 1491 in the function `bads.m` be changed from:

`        warning('The mesh attempted to expand above maximum size too many times. Try widening PLB and PUB.');
`

to

`        warning('bads:meshOverflow', 'The mesh attempted to expand above maximum size too many times. Try widening PLB and PUB.');
`
(PS: I see that I could set `options.MeshOverflowsWarning = Inf`. My motivation for the suggested code change is to still record the presence of the warning, but suppress the report to the console)

**Comment by lacerbi** [comment]
Great suggestion! I implemented it, and also added warning identifiers to the few other warnings in the BADS code. Thanks a lot for the input!
