### ISSUE TITLE
parallel function evaluations?

### ISSUE THREAD

**Issue by hyiltiz** [lacerbi/bads#7]
Is it possible to evaluate multiple cost functions at once, then produce the next set of likely parameters to evaluate, a.k.a. batch updating the internal model state with parallel function evaluation?

**Comment by lacerbi** [comment]
No, that's not supported in BADS. There is plenty of work on batch/parallel evaluation for Bayesian optimization, but it wouldn't be straightforward to implement as of now.

**Comment by lscoelho** [comment]
Is it possible to change the evolution strategy (ES, CMAES) inside of the BADS by another metaheuristics?
