### ISSUE TITLE
other metaheuristics

### ISSUE THREAD

**Issue by lscoelho** [lacerbi/bads#9]
Is it possible to change the evolution strategy (ES, CMAES) inside of the BADS by another metaheuristics?

**Comment by lacerbi** [comment]
Yes - the various Search heuristics are stored in the /search folder (different functions in the folder may or may not work; I was testing them a long time ago).
The default option, which is the one described in Section B.2 of the Appendix of the paper, is:

options.SearchMethod  = {@searchHedge,{{@searchES,1,1},{@searchES,2,1}}};

However, I recommend to be careful with it, and change it at your own risk.
BADS is a complex creature in that several components interact in non-trivial ways to yield an effective optimization algorithm. In particular, the fast approximate optimization of the acquisition function during the Search step is not just a "bad optimization" for which anything goes. There is information in the meta-heuristic itself about the shape of the target function (see Section B.2), so changing it will in general affect performance.
